name: Test
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - 'deploy/**'
      - '*.md'
  pull_request:
    branches:
      - '*'
env:
  GOPROXY: https://proxy.golang.org
  CGO_ENABLED: 0
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.39
          golangci-lint run --timeout=5m -v -c .golangci.yaml ./cmd/...

      - name: Test
        run: |
            go test -v ./cmd/...
